### ISSUE TITLE
Readme.md lacks proper description

### ISSUE THREAD

**Issue by ujjawal01** [fnplus/footsteps-extension#15]

**Comment by ujjawal01** [comment]
can i work on this issue ?

**Comment by anmolkaur18** [comment]
Can I work on this issue?

**Comment by xlogix** [comment]
Go for it!

**Comment by Riyagoel2** [comment]
I also want to work on this issue

**Comment by shreyakapoor08** [comment]
can i work on this issue?

**Comment by Chetanjain10** [comment]
please assign me this issue. This is going to be my first task

**Comment by xlogix** [comment]
@punisherz @anmolkaur18 Are you guys working on it? I'll be assigning it to others tomorrow.

**Comment by punisherz** [comment]
@xlogix I will make the pr tommorow.

**Comment by ujjawal01** [comment]
Yes I am working on it, I have updated the readme on my local machine my
window crashed can you wait till 11AM please,I will manage to do it by then

**Comment by anmolkaur18** [comment]
Yes !! Will make a pr by today evening

**Comment by shreyakapoor08** [comment]
If the issue is still pending, can I work on it ? @xlogix

**Comment by xlogix** [comment]
Go ahead!

**Comment by shreyakapoor08** [comment]
@xlogix Hey, PR raised 
Kindly check and let me know if any changes are required :)
