### ISSUE TITLE
Make a file CONTRIBUTING.md

### ISSUE THREAD

**Issue by shreyakapoor08** [fnplus/footsteps-extension#20]
Hey, 
Can I work on this issue and make a file specifying guidelines of how to contribute in the project.
I have provided it's short description which can be linked to this page for futher information @xlogix

**Comment by xlogix** [comment]
Assigned!

**Comment by xlogix** [comment]
Sounds good Shreya. Go ahead

**Comment by shreyakapoor08** [comment]
> Sounds good Shreya. Go ahead

PR raised, Kindly check and let me know if there is any corrections.
