### ISSUE TITLE
Improving the code quality from Codacy from grade B to A.

### ISSUE THREAD

**Issue by garimasingh128** [fnplus/footsteps-extension#38]
**Is your feature request related to a problem? Please describe.**
Improving the code quality from Codacy from grade B to A.

**Describe the solution you'd like**
Solving some issues like markdown guidelines, unexpected errors in syntax etc. to improve code quality.

**Comment by garimasingh128** [comment]
@xlogix I am a GSSOC 2020 participant. Kindly assign the issue to me if it is well-considerable.

**Comment by xlogix** [comment]
Assigned!
