### ISSUE TITLE
Replicate the build script in JS

### ISSUE THREAD

**Issue by arjunmahishi** [fnplus/footsteps-extension#8]
Currently, we build/transpile the code using `build.sh`. We need to rewrite this is in JS. Because, by making it a shell script, we are binding the development of this extension to Linux.  By having the script in JS, we will be able to build this is any platform that has nodeJS installed. 

The JS script can make use of the browserify APIs. This script should be written in `scripts/build.js`.

**Comment by Olyno** [comment]
Hi, can you assign me to this issue, please?

**Comment by arjunmahishi** [comment]
Thank you for your interest @Olyno, but issue is already resolved. We will be putting up more in sometime.
